name: ci
on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  IMAGE_NAME: sample-nodejs-app
  IMAGE_TAG: v1

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image
        env:
          DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        run: docker build . --file Dockerfile --tag $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG
      - name: Push docker image
        env:
          DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        run: docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG