name: Build and Push
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  push:
    branches: [master]
  pull_request:
    branches:    
      - 'releases/**'
  workflow_dispatch:

env:
  IMAGE_NAME: sample-nodejs-app
  IMAGE_TAG: v1
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}

jobs:
  DockerHub:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image
        run: docker build . --file Dockerfile --tag $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG
      - name: Push docker image to DockerHub
        run: docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG
  GithubContainerRegistry:
    permissions:
      packages: write
    needs: [DockerHub]
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - name: Build docker image
        run: docker build . --file Dockerfile --tag $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG
      - name: Push docker image to GHCR
        run: |
          docker tag $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:v1
          docker push ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:v1